[package]
name = "orbit-predictor"
version = "0.1.0"
authors = ["Mohammed Nawabuddin <MNahad@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tle-parser = "0.1.3"
