name: Test
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-20.04
    container: rust:1.56.0-slim-bullseye
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: cargo test
